### ISSUE TITLE
Always Position Error code:3

### ISSUE THREAD

**Issue by racosionic** [danielehrhardt/Ionic-2-Google-Maps-Marker-Cluster#3]
Always PositionError code :

PositionErrorcode: 3message: "Timeout expired"__proto__: PositionError

Testing on Android 7 (Moto Z Play and Samsung Tab S3) with localization always on.

Cordova version: 6.5.0

**Comment by danielehrhardt** [comment]
Is it possible that GPS is not activated on your Phone?

**Comment by racosionic** [comment]
Change what you indicated to me without positive results. 

```
getCurrentPosition() {
    this.loading = this.loadingCtrl.create({
      content: 'Searching Location ...'
    });
    this.loading.present();

    let locationOptions = { timeout: 10000, enableHighAccuracy: false};

    this.geolocation.getCurrentPosition(locationOptions).then(
      (position) => {  ...
```
I tried the same thing but on Android 6 and Andoird 5 and it works perfectly.

With Android 7 (Moto Z Play and Samsung TAB S3) never works but strangely if before running the application run google maps and hope to get my location close google maps and again run the application of your code that way works well , These steps are not required on Android 5 and 6.

I have tried to solve it so that it is not necessary to run Google Maps first but without success.

Could you tell me if I need any additional settings on my Mac?

I have the following settings:

Android SDK Tools - Rev: 25.2.5
Android Platform Tools - Rev: 25.0.5


Android 7.1.1 (API 25) - SDK Platform: 25

Sources for Android SDK not installed.


Android 7.0 (API 24) - Platform SDK: 25

Sources for Android SDK not installed.


Thanks

**Comment by danielehrhardt** [comment]
You can try to add Crosswalk to your Project. But i think this is a Problem with the Webview of Android 7.

**Comment by kapilSoni101** [comment]
@danielehrhardt: i got position error "timeout is expired" in the console after add timeout ?
