### ISSUE TITLE
Autocomplete not working on iOS

### ISSUE THREAD

**Issue by hayuki** [danielehrhardt/Ionic-2-Google-Maps-Marker-Cluster#5]
I followed your example from this project and implemented the autocomplete in my own Ionic project in the same way. It works like a charm on Android, but on iOS the autocomplete is not showing any place suggestions. Any idea why it would do that?

**Comment by hayuki** [comment]
Nevermind, the problem was that the Places Web API was not enabled in my Developer Console :) 

Thanks for this awesome project!

**Comment by danielehrhardt** [comment]
Hi,
Awesome.
